### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AndreaGiardini** [discourse/discourse-prometheus#1]
Here is the stackstrace... Unfortunately my Ruby is quite poor...

```
root@forum-testsite-io-4077246004-fnt2d:/opt/bitnami/discourse# RAILS_ENV=production bundle exec rake plugin:install repo=https://github.com/discourse/discourse-prometheus
Cloning into '/opt/bitnami/discourse/plugins/discourse-prometheus'...
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 202 (delta 94), reused 166 (delta 61), pack-reused 0
Receiving objects: 100% (202/202), 37.91 KiB | 517.00 KiB/s, done.
Resolving deltas: 100% (94/94), done.
root@forum-testsite-io-4077246004-fnt2d:/opt/bitnami/discourse# RAILS_ENV=production bundle exec rake assets:precompile
/opt/bitnami/discourse/lib/middleware/request_tracker.rb:47: warning: already initialized constant Middleware::RequestTracker::TRACK_VIEW
/opt/bitnami/discourse/lib/middleware/request_tracker.rb:47: warning: previous definition of TRACK_VIEW was here
/opt/bitnami/discourse/lib/middleware/request_tracker.rb:48: warning: already initialized constant Middleware::RequestTracker::CONTENT_TYPE
/opt/bitnami/discourse/lib/middleware/request_tracker.rb:48: warning: previous definition of CONTENT_TYPE was here
rake aborted!
NoMethodError: undefined method `register_detailed_request_logger' for Middleware::RequestTracker:Class
/opt/bitnami/discourse/plugins/discourse-prometheus/lib/reporter.rb:11:in `start'
/opt/bitnami/discourse/plugins/discourse-prometheus/plugin.rb:27:in `block in activate!'
/opt/bitnami/discourse/lib/plugin/instance.rb:209:in `block in notify_after_initialize'
/opt/bitnami/discourse/lib/plugin/instance.rb:207:in `each'
/opt/bitnami/discourse/lib/plugin/instance.rb:207:in `notify_after_initialize'
/opt/bitnami/discourse/config/application.rb:209:in `block (2 levels) in <class:Application>'
/opt/bitnami/discourse/config/application.rb:209:in `each'
/opt/bitnami/discourse/config/application.rb:209:in `block in <class:Application>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `each'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/opt/bitnami/discourse/config/environment.rb:5:in `<top (required)>'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/opt/bitnami/discourse/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/opt/bitnami/ruby/bin/bundle:23:in `load'
/opt/bitnami/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)

```

**Comment by xfalcox** [comment]
We don't support bitnami installs.

Follow the official install guide for a working Discourse.

**Comment by AndreaGiardini** [comment]
Unfortunately it looks like that guide does not support Kubernetes

**Comment by xfalcox** [comment]
@AndreaGiardini, you can.

For Kubernetes you want to bootstrap a web_only container using launcher as said in the guide.

After that, `docker tag` and `docker push` the image **local_discourse** image to your registry.

This resulting image is the one you should use in the container orchestration of choice.

Read more about this in:

https://meta.discourse.org/t/how-to-move-from-standalone-container-to-separate-web-and-data-containers/29413?u=falco

https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205?u=falco

**Comment by AndreaGiardini** [comment]
My local machine is different from my servers.

The builder makes assumptions about the hardware of the servers that are not correct

**Comment by tgxworld** [comment]
@AndreaGiardini You'll need to be on latest to run this plugin. Specifically, anything after https://github.com/tgxworld/discourse/commit/a4c539bade2c52782d3802ead965a06fa0b95da3
